### ISSUE TITLE
adding a second thermistor

### ISSUE THREAD

**Issue by Mungbeanz** [YuriiSalimov/NTC_Thermistor#12]
Hi,

Is it possible to add two thermistors eg A0 and A1 ?

**Comment by suoapvs** [comment]
Hi Mungbeanz

Yes, you can add two termistors to your project.
Example:
`Thermistor* firstThermistor = new NTC_Thermistor(A0, ...);`
`Thermistor* secondThermistor = new NTC_Thermistor(A1, ...);`

Regards, Yurii.
