### ISSUE TITLE
wifi going down

### ISSUE THREAD

**Issue by ghost** [YuriiSalimov/NTC_Thermistor#17]
you use 
delay();
and
sleep();
func`s.
Dont do it.
It is bad idea. Use millis() function or library based on internal timer.

**Comment by suoapvs** [comment]
This code was written 5 years ago. I have no idea what you're talking about anymore. I'm no longer interested in changing anything. You can download the code and make your changes.

**Comment by ghost** [comment]
Some lib`ss like AsyncWebServer or if you use wi-fi on your microcontroller, it going down when delay() or sleep() present in code.
it is very goon lib but in
AverageThermistor.cpp
and
SmoothThermistor.cpp
you must use millies()
some like this
```
unsignet int delay = 1000; // 1 second for example
unsignet int preM = 0;
loop(){
    if (millies() >= preM+delay){
        // your code here
        preM = millies;
}
```
good luck bro!

**Comment by ghost** [comment]
> This code was written 5 years ago. I have no idea what you're talking about anymore. I'm no longer interested in changing anything. You can download the code and make your changes.
Друже! ти з України?! 
Як ся маєш?
Я хотів би розпитати в тебе дещо про GoIT. Ми б не могли перемовитись парой слів?

**Comment by suoapvs** [comment]
I can change sleep() function:

```
inline void AverageThermistor::sleep() {
  unsigned long start = millis();
  while (millis() - start < this->delayTime) {
    // wait
  }
}
```
Review the code, please
