### ISSUE TITLE
Does not compile for non ESP32 platforms

### ISSUE THREAD

**Issue by joegatling** [YuriiSalimov/NTC_Thermistor#19]
I am running into an issue compiling version 2.1.0 for an Adafruit Trinket M0, which has a ATSAMD21E18 processor. When I try to compile it I get the following error:

`
.pio/libdeps/adafruit_trinket_m0/NTC_Thermistor/src/NTC_Thermistor.cpp: In member function 'virtual double NTC_Thermistor_ESP32::readVoltage()':
.pio/libdeps/adafruit_trinket_m0/NTC_Thermistor/src/NTC_Thermistor.cpp:125:17: error: 'analogReadMilliVolts' was not declared in this scope
  125 |  return (double)analogReadMilliVolts(this->pin) / (double)this->vref_mv * this->adcResolution;
      |                 ^~~~~~~~~~~~~~~~~~~~
`

I believe this is because the function analogReadMilliVolts() is an ESP32-sepcific function.

**Comment by joegatling** [comment]
I have a PR with a fix: https://github.com/suoapvs/NTC_Thermistor/pull/20

**Comment by suoapvs** [comment]
Done
