### ISSUE TITLE
setReadingsNumber in constructor doesn't take the given parameter

### ISSUE THREAD

**Issue by akonings** [YuriiSalimov/NTC_Thermistor#2]
Hi Yuri,

I came across your NTC library, and I liked it, because a lot of nasty calculations on NTC's is handled by it. But I ran across one litle thing; which is a result of a typo I think.

Please have a look at class function setReadmingsNumber, which takes a parameter newReadingsNumber.
The validate function is called with the class variable readingsNumber; which isn't initialized at that moment yet. 
In my setup the library worked great when I corrected the typo: 

Before:
void NTC_Thermistor::setReadingsNumber(const int newReadingsNumber) {
	this->readingsNumber = validate(readingsNumber, NTC_DEFAULT_READINGS_NUMBER);
}

( you see that newReadingsNumber parameter isn't used in the function ! ) 

After:
void NTC_Thermistor::setReadingsNumber(const int newReadingsNumber) {
	this->readingsNumber = validate(newReadingsNumber, NTC_DEFAULT_READINGS_NUMBER);
}

Because readingsNumber is the name of the class variable; the compiler doesn't give an error.

Hope this  helps you,

Regards, 

Arian.

**Comment by suoapvs** [comment]
Hi Arian!

Thank you for this message! Yes, this is my inattention!
The typo has already been fixed and a new version has been released.

Regards, Yurii.
