### ISSUE TITLE
How to get nominal resistance and nominal temperature

### ISSUE THREAD

**Issue by RJLABS** [YuriiSalimov/NTC_Thermistor#6]
i just buy cheap termistortor with spec:  NTC 10k±1% 3950, 
and i dont know how to get nominal resistance and nominal temperature from this termistor.
anyone can help me or give me a reference,

thanks for advice,

**Comment by suoapvs** [comment]
Hello!

For NTC 10k±1% 3950:
nominalResistance = 10 kOhm
nominalTemperature = 25 С
bValue = 3950

Regards, Yurii.

**Comment by RJLABS** [comment]
> Hello!
> 
> For NTC 10k±1% 3950:
> nominalResistance = 10 kOhm
> nominalTemperature = 25 С
> bValue = 3950
> 
> Regards, Yurii.

Thanks for quick respons Yurii,

Yesterday I tried with the parameters as above as you gave. but the temperature reading does not match with the actual temperature (I compare it with a thermometer).
reading from a thermistor 25.50 ^ C and from a calibrated thermometer 27.00 ^ C.

my question is how are the procedures for calibration this termistor?
can I increase or decrease the value of the results (+ or - result value). so the result match with my termometer or is there another method?

thanks for advice

**Comment by suoapvs** [comment]
Hello!

You can try to slightly change the value of the input parameters.
Also, I made some changes to the code. Сheck for updates, and try again.

Regards, Yurii.

**Comment by RJLABS** [comment]
i will check the update...and try...

the new update works perfectly,

thanks, Yurii.
