### ISSUE TITLE
INPUT_PULLUP

### ISSUE THREAD

**Issue by tomcunn** [YuriiSalimov/NTC_Thermistor#7]
The INPUT_PULLUP caused my readings to be off  by 50F. Changing to INPUT fixed the issue. The resistance values I was using 100K for reference and 100K thermistor. Using such high resistances will interact with the internal pullup resistor.  I am not sure the value of the internal resistor and I don't think the data sheet for the chip actually calls them out if I remember right, they just say high resistance.

**Comment by suoapvs** [comment]
Hello!

Replaced pinMode from INPUT_PULLUP to INPUT.
Check for updates.

Regards, Yurii.
